name: Generate Snake Animation

on:
  schedule:
    # Executa diariamente
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Gerar a cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: henriquetargino
          outputs: dist/snake.svg

      - name: Adicionar cobrinha ao repositório
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          publish_branch: github-pages
