name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: henriquetargino
          outputs: dist/snake.svg

      - name: Commit e Push da animação
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizar snake.svg com os commits mais recentes"
          file_pattern: dist/snake.svg
